### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by kristiandupont** [nunit/nunit.runners#9]
There is a NuGet package called Nunit.Runners, but installing that doesn't seem to do anything. I tried building this project with XS but I get a bunch of compiler errors. I started from http://www.alteridem.net/2015/03/25/nunit-3-0-test-runner-for-android-and-ios/ but I am not sure where to go from here. Is it in a working state?

**Comment by CharliePoole** [comment]
The NUnit.Runners package has been around for a long time and has nothing to do with this repository. It simply bundles the standard NUnit 2.6.4 runners for installation with nuget. We should probably rename this one to avoid confusion.

**Comment by rprouse** [comment]
There have been a few changes to the framework since this was written. I
will update it today.

**Comment by rprouse** [comment]
Fixed with PR #10 

The project wasn't building for you because it expected to find a pre-built copy of the main nunit.framework solution in your source tree. I have updated this solution to use the NuGet packages, so it should build for you assuming you have a valid Xamarin license.

I have also updated the README for this repository on how to build and use for testing. It is a bit involved at the moment, but updated project templates and NuGet binaries should make it trivial.

@kristiandupont, if you have time, give it a try and let me know if you have problems or suggestions.

@CharliePoole, do you think we should rename this repository to nunit.xamarin? I named it runners because I envisioned it including runners for other platforms, but we should probably keep them separate.

**Comment by CharliePoole** [comment]
@rprouse The existing 2.6.4 nunit.runners package probably can't change it's name without confusing people, so I guess this one needs a new name.

What would we call it if not xamarin? Devices? Mobile? What other runners do you anticipate having this architecture? Still, I have no problem with nunit.xamarin.

**Comment by kristiandupont** [comment]
Thank you for this update. We are currently experimenting with Xamarin's testrunner, but I might look into this if it doesn't work for us.

**Comment by rprouse** [comment]
I made a lot of progress this week and hope to get a beta release of this
out on NuGet next week. Thanks for the push.
